
title: Portal Sem Porteiras
email: portalsemporteiras@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  tamplate
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: portalsemporteiras
github_username:  portalsemporteiras


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

